import Phaser from 'phaser';
import './style.css';
import {W,H,TOP,BOTTOM,clamp,flight,difficulty,nextWorld,nextSafeGap,canHit} from './rules.mjs';

type Mode='classic'|'rescue';
type Power='boost'|'magnet'|'shield'|'slow'|'mega';
type Kind='laser'|'electric'|'drone'|'missile'|'machine'|'field';
type Obstacle={kind:Kind,x:number,y:number,w:number,h:number,speed:number,phase:number,warning:number,top?:number,bottom?:number,gfx:Phaser.GameObjects.Container};
type Coin={x:number,y:number,mega:boolean,gfx:Phaser.GameObjects.Container};
type Pickup={x:number,y:number,type:Power,gfx:Phaser.GameObjects.Container};
type Fx={gfx:Phaser.GameObjects.Arc|Phaser.GameObjects.Rectangle,life:number,vx:number,vy:number};
type Save={best:number,wallet:number,totalDistance:number,runs:number,missionClaims:string[],pendingMissionClaims:string[],achievements:string[],purchases:string[],equipped:string,equippedMocha:string,audio:{music:number,sfx:number,muted:boolean},reduced:boolean,quality:'high'|'low'};
const BASE=import.meta.env.BASE_URL;
const WORLDS=[{name:'SECRET LABORATORY',bg:0x071b30,mid:0x102c48,accent:0x24d7ff},{name:'NEON CITY',bg:0x160e39,mid:0x352062,accent:0xfe5aea},{name:'CYBER FACTORY',bg:0x1c1d2a,mid:0x3e3441,accent:0xffbe43},{name:'SPACE STATION',bg:0x090f2a,mid:0x172443,accent:0x89b8ff}];
const MISSIONS=[{id:'distance',name:'Travel 500 meters in one run',goal:500,award:75},{id:'coins',name:'Collect 100 coins in one run',goal:100,award:150},{id:'survive',name:'Survive 90 seconds',goal:90,award:200},{id:'avoid',name:'Safely pass 20 hazards',goal:20,award:175},{id:'mochaCoins',name:'Let Mocha collect 50 coins',goal:50,award:130},{id:'shields',name:'Activate Mocha’s shield 3 times',goal:3,award:220}];
const ITEMS=[{id:'classic',name:'Original Blue',who:'SAEID',cost:0,tint:0xffffff},{id:'ember',name:'Ember Jacket',who:'SAEID',cost:225,tint:0xffbb96},{id:'cyber',name:'Cyber Mint',who:'SAEID',cost:400,tint:0x9cffd5},{id:'royal',name:'Royal Indigo',who:'SAEID',cost:700,tint:0xc2b7ff},{id:'mochaGold',name:'Golden Harness',who:'MOCHA',cost:240,tint:0xffe8a8},{id:'mochaPink',name:'Pink Nebula',who:'MOCHA',cost:350,tint:0xffc4ed}];
function fresh():Save{return {best:0,wallet:0,totalDistance:0,runs:0,missionClaims:[],pendingMissionClaims:[],achievements:[],purchases:['classic'],equipped:'classic',equippedMocha:'none',audio:{music:.35,sfx:.65,muted:false},reduced:window.matchMedia('(prefers-reduced-motion:reduce)').matches,quality:'high'}}
function load():Save{try{const s=JSON.parse(localStorage.getItem('saeid-mocha-v1')||'null');return s?{...fresh(),...s,audio:{...fresh().audio,...s.audio}}:fresh()}catch{return fresh()}}
const save=load();const persist=()=>{try{localStorage.setItem('saeid-mocha-v1',JSON.stringify(save))}catch{}};
let game:Phaser.Game, runner:Runner|null=null,lastMode:Mode='classic';const screen=document.querySelector('#screen') as HTMLElement;const hud=document.querySelector('#hud') as HTMLElement;const hint=document.querySelector('#touch-hint') as HTMLElement;
const $=(sel:string)=>document.querySelector(sel) as HTMLElement;
const fmt=(n:number)=>Math.floor(n).toLocaleString('en-US');
const btn=(label:string,action:string,extra='')=>`<button class="btn ${extra}" data-action="${action}">${label}</button>`;
function show(html:string){screen.innerHTML=html;screen.classList.remove('hidden')}
function hide(){screen.innerHTML='';screen.classList.add('hidden')}
function btns(){screen.querySelectorAll('[data-action]').forEach(e=>e.addEventListener('click',()=>{audio.tap();act((e as HTMLElement).dataset.action||'')}))}
function openScene(name:string,data?:any){hide();hud.classList.add('hidden');hint.classList.add('hidden');game.scene.stop('Runner');runner=null;game.scene.start(name,data)}
function act(a:string){if(a==='play'||a==='rescue'){openScene('Runner',{mode:a==='play'?'classic':'rescue'});return}if(a==='menu'){openScene('Menu');return}if(a==='shop'){shopUI();return}if(a==='missions'){missionsUI();return}if(a==='achievements'){achievementsUI();return}if(a==='settings'){settingsUI();return}if(a==='help'){helpUI();return}if(a==='pause'){runner?.pause();return}if(a==='resume'){runner?.resume();return}if(a==='restart'){openScene('Runner',{mode:runner?.mode||lastMode});return}if(a.startsWith('buy:')){buy(a.slice(4));return}if(a.startsWith('claim:')){claim(a.slice(6));return}}
function panel(title:string,inner:string,footer=btn('← BACK','menu','ghost')){show(`<div class="panel"><div class="eyebrow">SAEID & MOCHA · ARCADE</div><h1>${title}</h1>${inner}<div class="actions">${footer}</div></div>`);btns()}
function menuUI(){const rescue=save.totalDistance>=1200;const body=`<div class="panel"><div class="menu-layout"><div><div class="eyebrow">THE JETPACK ADVENTURE</div><h1 class="hero-title">SAEID <span>&</span><br/>MOCHA</h1><p class="sub">One fearless pilot. One very grumpy copilot. Infinite possibilities.</p><div class="actions" style="justify-content:flex-start">${btn('▶ START ADVENTURE','play','gold')}${btn(rescue?'🐾 MOCHA RESCUE':'🔒 RESCUE · 1,200m','rescue',rescue?'':'ghost')}${btn('🛍 SHOP','shop','ghost')}${btn('🎯 MISSIONS','missions','ghost')}${btn('🏆 TROPHIES','achievements','ghost')}${btn('⚙ SETTINGS','settings','ghost')}${btn('? HOW TO PLAY','help','ghost')}</div><p class="small-note">PERSONAL BEST: ${fmt(save.best)} · BANK: ◈ ${fmt(save.wallet)} · RUNS: ${fmt(save.runs)}</p></div><div class="menu-characters"><span class="mocha-z" aria-hidden="true">Z<span>z</span><span>z</span></span><img src="${BASE}assets/saeid.webp" alt="Saeid with his jetpack"><img src="${BASE}assets/mocha.webp" alt="Mocha with her tiny jetpack"></div></div></div>`;show(body);screen.querySelector('[data-action="rescue"]')?.addEventListener('click',e=>{if(!rescue){e.stopImmediatePropagation();audio.tap();helpUI('Travel a total of 1,200 meters to unlock Mocha Rescue!')}} ,true);btns()}
function shopUI(){const itemHtml=ITEMS.map(i=>{const got=save.purchases.includes(i.id),eq=(i.who==='MOCHA'?save.equippedMocha:save.equipped)===i.id;return `<div class="tile"><div class="eyebrow">${i.who}</div><h3>${i.name}</h3><div style="width:48px;height:24px;background:#${i.tint.toString(16).padStart(6,'0')};border-radius:12px;margin:12px 0"></div><div class="price">${i.cost?'◈ '+i.cost:'FREE'}</div><div style="margin-top:12px">${btn(eq?'✓ EQUIPPED':got?'EQUIP':'BUY',`buy:${i.id}`,eq?'ghost':got?'':'gold')}</div></div>`}).join('');panel('Character Customization',`<p class="sub">Earn coins on runs. All upgrades are cosmetic; both heroes stay unmistakably themselves.</p><h3 class="price">◈ ${fmt(save.wallet)} AVAILABLE</h3><div class="grid2">${itemHtml}</div>`)}
function buy(id:string){const i=ITEMS.find(o=>o.id===id);if(!i)return;if(!save.purchases.includes(id)){if(save.wallet<i.cost){audio.error();return}save.wallet-=i.cost;save.purchases.push(id)}if(i.who==='MOCHA')save.equippedMocha=id;else save.equipped=id;persist();audio.power();shopUI()}
function missionsUI(){
  const html='<p class="sub">Finish each challenge in a single run. Completed missions can be claimed here even after reopening the game.</p>'+
    MISSIONS.map(m=>{
      const status=save.missionClaims.includes(m.id)
        ? '<span class="tag">✓ CLAIMED</span>'
        : save.pendingMissionClaims.includes(m.id)
        ? btn('CLAIM ◈ '+m.award,'claim:'+m.id,'gold')
        : '<span class="tag">CHALLENGE</span>';
      return '<div class="row-item"><div><b>'+m.name+'</b><div class="tiny">Reward ◈ '+m.award+'</div></div>'+status+'</div>';
    }).join('');
  panel('Missions',html);
}
function achievementsUI(){const arr=[['first','First Flight','Finish your first run'],['rookie','Lab Escapee','Travel 500 meters in total'],['speed','Neon Navigator','Travel 3,000 meters in total'],['collector','Coin Collector','Bank 500 coins'],['guardian','Best Buddies','Use Mocha’s shield'],['rescue','Mocha Hero','Finish a Rescue run']];panel('Hall of Heroes',`<div class="grid2">${arr.map(([id,n,d])=>`<div class="tile"><h3>${save.achievements.includes(id)?'🏆':'🔒'} ${n}</h3><div class="tiny">${d}</div></div>`).join('')}</div>`)}
function settingsUI(){panel('Settings',`<div class="switch"><label for="music">Music</label><input id="music" type="range" min="0" max="100" value="${save.audio.music*100}"><span id="mv">${Math.round(save.audio.music*100)}%</span></div><div class="switch"><label for="sfx">Sound effects</label><input id="sfx" type="range" min="0" max="100" value="${save.audio.sfx*100}"><span id="sv">${Math.round(save.audio.sfx*100)}%</span></div><div class="switch"><label><input id="mute" type="checkbox" ${save.audio.muted?'checked':''}> Mute all audio</label></div><div class="switch"><label><input id="reduced" type="checkbox" ${save.reduced?'checked':''}> Reduced motion</label></div><div class="switch"><label><input id="low" type="checkbox" ${save.quality==='low'?'checked':''}> Low quality visual effects</label></div><p class="tiny">Progress is saved to this browser only. No tracking or purchases.</p>`);['music','sfx'].forEach(id=>$('#'+id).addEventListener('input',e=>{const v=Number((e.target as HTMLInputElement).value)/100;(save.audio as any)[id]=v;$('#'+(id==='music'?'mv':'sv')).textContent=Math.round(v*100)+'%';persist();audio.adjust()}));$('#mute').addEventListener('change',e=>{save.audio.muted=(e.target as HTMLInputElement).checked;persist();audio.adjust()});$('#reduced').addEventListener('change',e=>{save.reduced=(e.target as HTMLInputElement).checked;persist()});$('#low').addEventListener('change',e=>{save.quality=(e.target as HTMLInputElement).checked?'low':'high';persist()})}
function helpUI(message=''){panel('Mission Briefing',`<p class="sub">${message||'Saeid flies automatically while Mocha handles the precious loot. Dodge the lab defenses and make it to the stars!'}</p><div class="grid2"><div class="tile"><h3>⌨ Desktop</h3>Hold <b>SPACE</b> / <b>↑</b> to fly, release to fall. <b>M</b> = Mocha shield, <b>P</b> / <b>ESC</b> = pause.</div><div class="tile"><h3>☝ Mobile</h3>Hold anywhere in the game to fly. Release to descend. Tap the <b>🐾 paw</b> for a shield.</div></div><p class="sub">Pick up gold coins, rare mega coins, shields, magnets, time-benders and turbo boosters. Mocha automatically retrieves nearby coins and protects you every 30 seconds.</p>`,btn('▶ PLAY','play','gold')+btn('← MENU','menu','ghost'))}
function claim(id:string){
  if(save.missionClaims.includes(id)||!save.pendingMissionClaims.includes(id))return;
  const mission=MISSIONS.find(m=>m.id===id);if(!mission)return;
  save.wallet+=mission.award;
  save.missionClaims.push(id);
  save.pendingMissionClaims=save.pendingMissionClaims.filter(key=>key!==id);
  persist();audio.power();
  if(runner?.ended)runner.endUI();else missionsUI();
}
class SoundLab{ctx:AudioContext|null=null;tick=0;musicTimer:number|null=null;musicGain:GainNode|null=null;world=0;unlocked=false;
 unlock(){if(!this.ctx){try{this.ctx=new AudioContext()}catch{return}}this.ctx.resume().catch(()=>{});this.unlocked=true;if(this.musicTimer===null)this.startMusic()}
 tone(f:number,d=.12,type:OscillatorType='sine',gain=.13,slide=0){if(!this.ctx||save.audio.muted||!save.audio.sfx)return;const now=this.ctx.currentTime;const osc=this.ctx.createOscillator(),g=this.ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(f,now);if(slide)osc.frequency.exponentialRampToValueAtTime(Math.max(30,f+slide),now+d);g.gain.setValueAtTime(.001,now);g.gain.linearRampToValueAtTime(gain*save.audio.sfx,now+.01);g.gain.exponentialRampToValueAtTime(.001,now+d);osc.connect(g).connect(this.ctx.destination);osc.start(now);osc.stop(now+d+.015)}
 tap(){this.unlock();this.tone(690,.045,'sine',.06)}coin(){this.tone(840,.11,'triangle',.11,340)}power(){this.tone(520,.28,'sawtooth',.09,480)}shield(){this.tone(240,.4,'sine',.14,620)}hit(){this.tone(230,.43,'sawtooth',.2,-185)}error(){this.tone(135,.11,'square',.07)}jet(){const now=performance.now();if(now-(this as any).jetLast>135){(this as any).jetLast=now;this.tone(90,.07,'triangle',.021,120)}}
 startMusic(){if(!this.ctx)return;this.musicTimer=window.setInterval(()=>{if(!this.ctx||save.audio.muted||!save.audio.music||!runner||runner.paused||runner.ended)return;const riffs=[[164,196,246,196,164,220,246,294],[174,220,261,220,174,261,349,293],[146,196,220,196,146,220,293,246],[130,164,196,261,196,164,196,293]];const f=riffs[this.world][this.tick%8];this.musicNote(f,.13,.045);if(this.tick%4===0)this.musicNote(f/2,.2,.09,'triangle');this.tick++},185)}
 musicNote(f:number,d:number,gain:number,type:OscillatorType='square'){if(!this.ctx)return;const now=this.ctx.currentTime,osc=this.ctx.createOscillator(),g=this.ctx.createGain();osc.type=type;osc.frequency.value=f;g.gain.setValueAtTime(.001,now);g.gain.linearRampToValueAtTime(gain*save.audio.music,now+.01);g.gain.exponentialRampToValueAtTime(.001,now+d);osc.connect(g).connect(this.ctx.destination);osc.start(now);osc.stop(now+d+.01)}adjust(){} }
const audio=new SoundLab();
function circle(scene:Phaser.Scene,x:number,y:number,r:number,c:number,a=1){return scene.add.circle(x,y,r,c,a)}
class Menu extends Phaser.Scene{stars:Phaser.GameObjects.Arc[]=[];constructor(){super('Menu')}create(){this.cameras.main.setBackgroundColor('#081730');const bg=this.add.graphics();for(let i=0;i<36;i++){const y=i*22;bg.fillStyle(i%2?0x142947:0x10233c,.9);bg.fillRect(0,y,W,12);bg.fillStyle(0x205882,.14);bg.fillRect((i*79)%W,y+13,240,3)}for(let i=0;i<18;i++){let x=i*85+5;this.stars.push(circle(this,x,(i*113)%H,1+(i%3),i%2?0x46e8ff:0xffd44c,.45))}this.add.rectangle(W/2,H-110,W,155,0x030915,.45);this.add.text(W-32,H-30,'ORIGINAL ARCADE ADVENTURE  /  EST. 2026',{color:'#a3dcff',fontSize:'14px',fontStyle:'bold'}).setOrigin(1);menuUI();this.events.once('shutdown',()=>this.stars=[])}update(t:number){if(save.reduced)return;this.stars.forEach((s,i)=>s.y+=.13+(i%4)*.12);this.stars.forEach(s=>{if(s.y>H)s.y=0})}}
class Runner extends Phaser.Scene{mode:Mode='classic';distance=0;score=0;runCoins=0;mochaCoins=0;avoided=0;shieldsUsed=0;elapsed=0;speed=345;playerY=345;vy=0;hold=false;paused=false;ended=false;shield=0;shieldCooldown=0;magnet=0;boost=0;slow=0;invulnerable=0;spawner=0;coinSpawner=0;pickupTimer=0;missileDelay=13;obstacles:Obstacle[]=[];coinDrops:Coin[]=[];pickups:Pickup[]=[];effects:Fx[]=[];particlePool:Phaser.GameObjects.Arc[]=[];completed:string[]=[];world=-1;hudElapsed=0;bgLayers:Phaser.GameObjects.Graphics[]=[];saeid!:Phaser.GameObjects.Image;mocha!:Phaser.GameObjects.Image;jetFlame!:Phaser.GameObjects.Graphics;mochaFlame!:Phaser.GameObjects.Graphics;shieldGfx!:Phaser.GameObjects.Arc;mochaHalo!:Phaser.GameObjects.Arc;jetColor=0xff8c09;rescueTokens=0;rescueTimer=0;lastGapY=340;worldLabel:Phaser.GameObjects.Text|null=null;abilityBtn!:HTMLElement;touchStart=(e:TouchEvent)=>{if((e.target as HTMLElement).closest('button,#screen'))return;this.hold=true};touchEnd=()=>this.hold=false;pointerDown=()=>{this.hold=true;audio.unlock()};pointerUp=()=>this.hold=false;blur=()=>{this.hold=false;if(!this.ended&&!this.paused)this.pause()};visibility=()=>{if(document.hidden)this.blur()};
 constructor(){super('Runner')}
 init(data:{mode?:Mode}){this.mode=data?.mode||'classic';lastMode=this.mode;this.distance=0;this.score=0;this.runCoins=0;this.mochaCoins=0;this.avoided=0;this.shieldsUsed=0;this.elapsed=0;this.speed=345;this.playerY=345;this.vy=0;this.hold=false;this.paused=false;this.ended=false;this.shield=0;this.shieldCooldown=0;this.magnet=0;this.boost=0;this.slow=0;this.invulnerable=0;this.spawner=.8;this.coinSpawner=.3;this.pickupTimer=7;this.missileDelay=13;this.obstacles=[];this.coinDrops=[];this.pickups=[];this.effects=[];this.particlePool=[];this.hudElapsed=0;this.completed=[];this.world=-1;this.bgLayers=[];this.worldLabel=null;this.rescueTokens=0;this.rescueTimer=0;this.lastGapY=340}
 preload(){this.load.on('loaderror',()=>{show('<div class="panel center"><h1>Asset loading failed</h1><p>Check your connection, then reload the game.</p></div>')});this.load.image('saeid',BASE+'assets/saeid.webp');this.load.image('mocha',BASE+'assets/mocha.webp')}
 create(){runner=this;this.cameras.main.setBackgroundColor('#07152d');this.makeWorld(0);this.jetFlame=this.add.graphics().setDepth(12);this.mochaFlame=this.add.graphics().setDepth(12);this.saeid=this.add.image(265,this.playerY,'saeid').setDisplaySize(155,200).setDepth(15);const skin=ITEMS.find(x=>x.id===save.equipped);if(skin&&skin.who==='SAEID'){this.saeid.setTint(skin.tint);this.jetColor=skin.id==='ember'?0xff6a13:skin.id==='cyber'?0x58ffd3:skin.id==='royal'?0x9e80ff:0xff8c09}else this.jetColor=0xff8c09;this.mochaHalo=circle(this,108,this.playerY+85,64,0xffd44b,.075).setStrokeStyle(3,0xffd44b,.7).setDepth(16);this.mocha=this.add.image(108,this.playerY+85,'mocha').setDisplaySize(113,105).setDepth(17);const mskin=ITEMS.find(x=>x.id===save.equippedMocha);if(mskin&&mskin.who==='MOCHA'){this.mochaHalo.setFillStyle(mskin.tint,.13).setStrokeStyle(5,mskin.tint,.87)};this.shieldGfx=circle(this,265,this.playerY,106,0x4adfff,.07).setStrokeStyle(5,0x75edff,.8).setVisible(false).setDepth(18);hud.classList.remove('hidden');hint.classList.remove('hidden');hide();$('#ability').onclick=e=>{e.stopPropagation();audio.unlock();this.useShield()};$('#pause').onclick=e=>{e.stopPropagation();this.pause()};this.input.keyboard?.on('keydown-SPACE',this.keyDown,this);this.input.keyboard?.on('keyup-SPACE',this.keyUp,this);this.input.keyboard?.on('keydown-UP',this.keyDown,this);this.input.keyboard?.on('keyup-UP',this.keyUp,this);this.input.keyboard?.on('keydown-M',this.keyM,this);this.input.keyboard?.on('keydown-P',this.keyPause,this);this.input.keyboard?.on('keydown-ESC',this.keyPause,this);this.input.on('pointerdown',this.pointerDown);this.input.on('pointerup',this.pointerUp);this.input.on('pointerupoutside',this.pointerUp);document.addEventListener('touchend',this.touchEnd);document.addEventListener('touchcancel',this.touchEnd);window.addEventListener('blur',this.blur);document.addEventListener('visibilitychange',this.visibility);this.events.once('shutdown',()=>this.clean());save.runs++;persist();this.drawHud()}
 keyDown(e:KeyboardEvent){e.preventDefault();this.hold=true;audio.unlock()}keyUp(e:KeyboardEvent){e.preventDefault();this.hold=false}keyM(e:KeyboardEvent){e.preventDefault();this.useShield()}keyPause(e:KeyboardEvent){e.preventDefault();if(this.paused)this.resume();else this.pause()}
 clean(){this.input.keyboard?.off('keydown-SPACE',this.keyDown,this);this.input.keyboard?.off('keyup-SPACE',this.keyUp,this);this.input.keyboard?.off('keydown-UP',this.keyDown,this);this.input.keyboard?.off('keyup-UP',this.keyUp,this);this.input.keyboard?.off('keydown-M',this.keyM,this);this.input.keyboard?.off('keydown-P',this.keyPause,this);this.input.keyboard?.off('keydown-ESC',this.keyPause,this);this.input.off('pointerdown',this.pointerDown);this.input.off('pointerup',this.pointerUp);this.input.off('pointerupoutside',this.pointerUp);document.removeEventListener('touchend',this.touchEnd);document.removeEventListener('touchcancel',this.touchEnd);window.removeEventListener('blur',this.blur);document.removeEventListener('visibilitychange',this.visibility);this.clearEntities();hud.classList.add('hidden');hint.classList.add('hidden')}
 clearEntities(){[...this.obstacles,...this.coinDrops,...this.pickups].forEach(e=>e.gfx.destroy());this.effects.forEach(f=>f.gfx.destroy());this.particlePool.forEach(g=>g.destroy());this.particlePool=[];this.obstacles=[];this.coinDrops=[];this.pickups=[];this.effects=[]}
 makeWorld(index:number){if(this.world===index)return;this.world=index;audio.world=index;audio.tick=0;this.bgLayers.forEach(o=>o.destroy());this.bgLayers=[];const w=WORLDS[index];this.cameras.main.setBackgroundColor(w.bg);const far=this.add.graphics().setDepth(-5);const mid=this.add.graphics().setDepth(-4);const near=this.add.graphics().setDepth(-3);const lines=this.add.graphics().setDepth(-2);this.bgLayers.push(far,mid,near,lines);let seed=index*31+9;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};far.fillStyle(w.mid,.5);for(let i=0;i<28;i++){const x=i*67-70,h=70+rand()*260;far.fillRect(x,H-h-80,50+rand()*46,h);far.fillStyle(w.accent,.2);for(let j=0;j<8;j++)far.fillRect(x+6+(j%2)*18,H-h-55+j*24,7,8);far.fillStyle(w.mid,.5)}mid.fillStyle(w.mid,.84);for(let i=0;i<19;i++){const x=i*105-70,h=100+rand()*260;mid.fillRoundedRect(x,H-h-45,90,h,5);mid.fillStyle(w.accent,.23);for(let j=0;j<8;j++)mid.fillRect(x+12+(j%3)*25,H-h-17+j*25,9,4);mid.fillStyle(w.mid,.84)}near.fillStyle(0x051322,.92);near.fillRect(0,H-65,W+340,65);near.lineStyle(4,w.accent,.45);near.lineBetween(0,H-68,W+340,H-68);near.lineStyle(2,w.accent,.16);for(let x=0;x<W+340;x+=94)near.lineBetween(x,H-60,x+48,H);if(index===3){far.fillStyle(0x3f7bb9,.35);far.fillCircle(1060,320,175);far.lineStyle(8,0x91ceff,.14);far.strokeCircle(1060,320,180)}if(index===1){mid.fillStyle(0xff5fd5,.8);mid.fillRoundedRect(830,170,190,50,9);mid.fillStyle(0x100b30);mid.fillRect(845,187,160,17)}if(index===0){far.lineStyle(7,0x1db4da,.15);for(let x=0;x<W;x+=160)far.strokeRect(x,40,120,H-155)}if(index===2){near.lineStyle(9,0xffa92f,.23);for(let x=20;x<W;x+=125)near.lineBetween(x,580,x+100,480)}this.worldLabel?.destroy();this.worldLabel=this.add.text(24,H-32,w.name,{fontFamily:'monospace',fontSize:'17px',color:'#b0d8e5'}).setAlpha(.55).setDepth(-1).setScrollFactor(0);this.flashLabel(w.name)}
 flashLabel(s:string){const t=this.add.text(W/2,155,s,{fontFamily:'system-ui',fontSize:'31px',fontStyle:'900',color:'#b9f6ff',stroke:'#041730',strokeThickness:6}).setOrigin(.5).setDepth(40).setAlpha(0);this.tweens.add({targets:t,alpha:1,y:138,duration:350,yoyo:true,hold:1400,onComplete:()=>t.destroy()})}
 emit(x:number,y:number,c=0xffd64a,n=6){if(this.effects.length>155)return;if(save.quality==='low'||save.reduced)n=Math.ceil(n/3);for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=70+Math.random()*180;const g=this.particlePool.pop()||circle(this,x,y,2+Math.random()*3,c,.9);g.setPosition(x,y).setFillStyle(c,.9).setAlpha(.9).setVisible(true).setActive(true).setDepth(30);this.effects.push({gfx:g,life:.38+Math.random()*.38,vx:Math.cos(a)*s,vy:Math.sin(a)*s})}}
 flame(t:number){this.jetFlame.clear();this.mochaFlame.clear();if(this.ended)return;const flare=this.hold?1.35:.55;const wob=Math.sin(t*.019)*7;this.jetFlame.fillStyle(this.jetColor,.9);this.jetFlame.fillTriangle(this.saeid.x-49,this.saeid.y+34,this.saeid.x-26,this.saeid.y+53,this.saeid.x-102-flare*19,this.saeid.y+124+wob);this.jetFlame.fillStyle(0xfff4a8,.93);this.jetFlame.fillTriangle(this.saeid.x-44,this.saeid.y+39,this.saeid.x-34,this.saeid.y+49,this.saeid.x-79-flare*14,this.saeid.y+99+wob);this.mochaFlame.fillStyle(0xffc12a,.78);this.mochaFlame.fillTriangle(this.mocha.x-36,this.mocha.y+5,this.mocha.x-25,this.mocha.y+18,this.mocha.x-64,this.mocha.y+45+wob*.3)}
 addCoin(x:number,y:number,mega=false){const g=this.add.container(x,y).setDepth(9);const outer=circle(this,0,0,mega?24:14,0xf9c52c).setStrokeStyle(3,0xffef9b,1);const dot=circle(this,0,0,mega?11:6,0xd38e12);g.add([outer,dot]);this.coinDrops.push({x,y,mega,gfx:g})}
 coinsPattern(){const x=W+40,y=clamp(this.lastGapY+Phaser.Math.Between(-100,100),TOP+45,BOTTOM-45),n=6+Math.floor(Math.random()*3),pattern=Phaser.Math.Between(0,3);for(let i=0;i<n;i++){const dy=pattern===0?0:pattern===1?Math.sin(i/n*Math.PI)*-80:pattern===2?(i%2?60:-30):Math.sin(i/n*Math.PI*2)*50;this.addCoin(x+i*49,y+dy)}this.coinSpawner=1.3+Math.random()*1.2}
 pickup(){const pool:Power[]=['boost','magnet','shield','slow','mega'];const type=pool[Phaser.Math.Between(0,4)],x=W+110,y=Phaser.Math.Between(TOP+80,BOTTOM-90);const c={boost:0xff9b25,magnet:0xff5adb,shield:0x4be8ff,slow:0xc2b0ff,mega:0xffe257}[type];const g=this.add.container(x,y).setDepth(11);g.add([circle(this,0,0,24,c,.19).setStrokeStyle(4,c,.95),this.add.text(0,0,({boost:'⚡',magnet:'◎',shield:'⬡',slow:'◷',mega:'◈'} as any)[type],{fontSize:'29px',fontStyle:'bold',color:'#ffffff'}).setOrigin(.5)]);this.pickups.push({x,y,type,gfx:g});this.pickupTimer=8+Math.random()*6}
 obstacle(){const diff=difficulty(this.distance);let gap=diff.gap;let center=nextSafeGap(this.lastGapY,Phaser.Math.Between(-115,115),gap);this.lastGapY=center;const types:Kind[]=['laser','electric','drone','machine','field'];let type=types[Phaser.Math.Between(0,Math.min(types.length-1,Math.floor(this.distance/900)+1))];let x=W+115;const g=this.add.container(x,0).setDepth(10);let o:Obstacle={kind:type,x,y:center,w:45,h:gap,speed:0,phase:Math.random()*6,warning:0,top:center-gap/2,bottom:center+gap/2,gfx:g};const col=type==='laser'?0xff426f:type==='electric'?0x4be9ff:type==='field'?0xbd5dff:type==='machine'?0xffb342:0xff5965;
 if(type==='drone'){o.y=center;o.h=68;o.w=90;g.add([this.add.rectangle(0,center,92,37,0x15263f).setStrokeStyle(3,0xff5a73),circle(this,0,center,21,0xff3455,.8),this.add.rectangle(-58,center,22,6,0x88daff),this.add.rectangle(58,center,22,6,0x88daff)]);}else{const top=Math.max(0,o.top||0),bottom=o.bottom||H;g.add([this.add.rectangle(0,top/2,48,top,0x112b46,.95).setStrokeStyle(4,col),this.add.rectangle(0,bottom+(H-bottom)/2,48,H-bottom,0x112b46,.95).setStrokeStyle(4,col),this.add.rectangle(0,(o.top||0)-12,68,23,col,.9),this.add.rectangle(0,(o.bottom||0)+12,68,23,col,.9)]);if(type==='laser')g.add([this.add.rectangle(-30,(o.top||0)/2,5,top,col,.65),this.add.rectangle(-30,(o.bottom||0)+(H-bottom)/2,5,H-bottom,col,.65)]);}
 (o as any).baseY=center;this.obstacles.push(o);this.spawner=diff.interval+Math.random()*.44}
 missile(){const x=W+165,y=clamp(this.playerY+Phaser.Math.Between(-155,155),TOP+25,BOTTOM-25),g=this.add.container(x,y).setDepth(13);const warn=this.add.text(W-145,y,'⚠  INCOMING',{fontSize:'17px',fontFamily:'monospace',color:'#ffb353',backgroundColor:'#57130e'}).setDepth(34);this.time.delayedCall(1200,()=>{warn.destroy();if(!this.ended&&!this.paused){g.add([this.add.triangle(0,0,-34,-12,26,0,-34,12,0xe1e9f6),this.add.rectangle(-25,0,23,10,0xff7b26),this.add.rectangle(0,0,15,7,0xff6b50)]);this.obstacles.push({kind:'missile',x,y,w:77,h:29,speed:165,phase:0,warning:0,gfx:g})}else g.destroy()});this.missileDelay=11+Math.random()*7}
 useShield(){if(this.ended||this.paused||this.shieldCooldown>0)return;this.shield=1;this.shieldCooldown=30;this.shieldsUsed++;this.emit(this.saeid.x,this.playerY,0x55edff,23);audio.shield();this.drawHud()}
 power(p:Power){if(p==='mega'){this.runCoins+=50;this.score+=500;audio.coin();return}if(p==='shield')this.shield=1;if(p==='boost')this.boost=5.5;if(p==='magnet')this.magnet=9;if(p==='slow')this.slow=5;audio.power();this.emit(265,this.playerY,0xffffff,16);this.drawHud()}
 getCoin(c:Coin,mocha=false){if(this.mode==='rescue'&&c.mega){this.rescueTokens++;if(this.rescueTokens%3===0){this.score+=1500;this.flashLabel('3 RESCUE SIGNALS SAVED!');this.emit(c.x,c.y,0x79ebff,20)}}this.runCoins+=c.mega?50:1;this.score+=c.mega?500:10;if(mocha)this.mochaCoins+=c.mega?5:1;this.emit(c.x,c.y,0xffd743,c.mega?13:5);audio.coin();c.gfx.destroy();this.coinDrops.splice(this.coinDrops.indexOf(c),1)}
 collide(){if(this.boost>0||this.invulnerable>0)return;if(this.shield){this.shield=0;this.invulnerable=1.6;this.shieldGfx.setVisible(false);this.cameras.main.shake(170,.009);this.emit(265,this.playerY,0x5fddff,22);audio.shield();return}this.gameOver()}
 update(time:number,delta:number){if(this.ended||this.paused)return;const dt=Math.min(.044,delta/1000);let sim=dt*(this.slow>0?.55:1);this.elapsed+=dt;this.distance+=(this.speed+(this.boost>0?200:0))*sim*.115;const df=difficulty(this.distance);this.speed=df.speed;if(this.shieldCooldown>0)this.shieldCooldown=Math.max(0,this.shieldCooldown-dt);for(const key of ['magnet','boost','slow','invulnerable'] as const)this[key]=Math.max(0,this[key]-dt);const p=flight(this.playerY,this.vy,this.hold,dt);this.playerY=p.y;this.vy=p.vy;this.saeid.y=this.playerY+(save.reduced?0:Math.sin(time*.011)*(this.hold?2:4));this.saeid.rotation=clamp(this.vy/3000,-.14,.16)+(save.reduced?0:Math.sin(time*.008)*.016);this.saeid.setDisplaySize(155*(1+(save.reduced?0:Math.sin(time*.022)*.009)),200*(1-(save.reduced?0:Math.sin(time*.022)*.008)));this.saeid.setAlpha(this.invulnerable>0&&Math.floor(time/100)%2? .55:1);this.mocha.x+=(120+Math.sin(time*.0015)*13-this.mocha.x)*(1-Math.exp(-7.7*dt));this.mocha.y+=(this.playerY+80+Math.sin(time*.006)*18-this.mocha.y)*(1-Math.exp(-4.7*dt));this.mocha.rotation=save.reduced?0:Math.sin(time*.006)*.055;this.mochaHalo.setPosition(this.mocha.x,this.mocha.y).setScale(1+(save.reduced?0:Math.sin(time*.006)*.05));this.mocha.setDisplaySize(113*(1+(save.reduced?0:Math.sin(time*.012)*.012)),105);this.flame(time);this.shieldGfx.setPosition(265,this.playerY).setVisible(this.shield>0);if(this.shield>0)this.shieldGfx.setScale(1+Math.sin(time*.01)*.035);if(this.hold&&Math.random()>.66)audio.jet();const world=nextWorld(this.distance);if(world!==this.world)this.makeWorld(world);this.bgLayers.forEach((g,i)=>g.x=-(this.distance*[.23,.46,.87,1.06][i]%250));this.spawner-=sim;this.coinSpawner-=sim;this.pickupTimer-=sim;this.missileDelay-=sim;if(this.spawner<=0)this.obstacle();if(this.coinSpawner<=0)this.coinsPattern();if(this.pickupTimer<=0)this.pickup();if(this.missileDelay<=0&&this.distance>550){if(this.obstacles.some(o=>o.x>W-150))this.missileDelay=.85;else this.missile()}if(this.mode==='rescue'){this.rescueTimer+=dt;if(this.rescueTimer>=12){this.rescueTimer=0;this.addCoin(W+60,clamp(this.playerY+Phaser.Math.Between(-100,100),TOP+30,BOTTOM-30),true)}}const speed=(this.speed+(this.boost>0?200:0))*sim;
 for(let i=this.obstacles.length-1;i>=0;i--){const o=this.obstacles[i];o.x-=speed+o.speed*sim;o.phase+=dt*2.4;if(o.kind==='drone'){o.y=(o as any).baseY+Math.sin(o.phase)*32;o.gfx.y=o.y-(o as any).baseY}else if(o.kind==='machine'){const shift=Math.sin(o.phase)*30;o.gfx.y=shift;o.top=(o as any).baseY-o.h/2+shift;o.bottom=(o as any).baseY+o.h/2+shift}else if(o.kind==='laser'){o.gfx.alpha=Math.sin(o.phase*2.1)>-.62?1:.24}if(o.kind==='missile')o.y+=(this.playerY-o.y)*Math.min(.014,dt*.36);o.gfx.x=o.x;if(o.kind==='missile')o.gfx.y=o.y;if(o.x<140&&!((o as any).passed)){this.avoided++;(o as any).passed=true}const hit=o.kind==='laser'&&o.gfx.alpha<.5?false:o.kind==='drone'||o.kind==='missile'?canHit({x:265,y:this.playerY,w:77,h:113},{x:o.x,y:o.y,w:o.w,h:o.h}):Math.abs(o.x-265)<47&&(this.playerY-51<(o.top||0)||this.playerY+48>(o.bottom||H));if(hit)this.collide();if(this.ended)return;if(o.x< -155){o.gfx.destroy();this.obstacles.splice(i,1)}}
 for(let i=this.coinDrops.length-1;i>=0;i--){const c=this.coinDrops[i];c.x-=speed;c.gfx.x=c.x;c.gfx.rotation+=dt*2.8;const dx=this.mocha.x-c.x,dy=this.mocha.y-c.y;const r=this.magnet>0?260:83;if(dx*dx+dy*dy<r*r){if(this.magnet>0){c.x+=dx*dt*5;c.y+=dy*dt*5;c.gfx.y=c.y}if(Math.abs(dx)<44&&Math.abs(dy)<53){this.getCoin(c,true);continue}}if(Math.abs(c.x-265)<57&&Math.abs(c.y-this.playerY)<86){this.getCoin(c);continue}if(c.x< -40){c.gfx.destroy();this.coinDrops.splice(i,1)}}
 for(let i=this.pickups.length-1;i>=0;i--){const p=this.pickups[i];p.x-=speed;p.gfx.x=p.x;p.gfx.rotation+=dt*.9;if(Math.abs(p.x-265)<74&&Math.abs(p.y-this.playerY)<90){this.power(p.type);p.gfx.destroy();this.pickups.splice(i,1);continue}if(p.x< -70){p.gfx.destroy();this.pickups.splice(i,1)}}
 for(let i=this.effects.length-1;i>=0;i--){const f=this.effects[i];f.life-=dt;f.gfx.x+=f.vx*dt;f.gfx.y+=f.vy*dt;f.vy+=220*dt;f.gfx.alpha=clamp(f.life*2,0,1);if(f.life<=0){const g=f.gfx as Phaser.GameObjects.Arc;g.setVisible(false).setActive(false);if(this.particlePool.length<160)this.particlePool.push(g);else g.destroy();this.effects.splice(i,1)}}this.score+=dt*5;this.updateMissions();this.hudElapsed+=dt;if(this.hudElapsed>=.1){this.hudElapsed=0;this.drawHud()}}
 drawHud(){$('#distance').textContent=fmt(this.distance);$('#coins').textContent=fmt(this.runCoins);$('#score').textContent=fmt(this.score);$('#cooldown').textContent=this.shieldCooldown>0?`${Math.ceil(this.shieldCooldown)}s`:this.shield?'SHIELDED':'READY';$('#ability').classList.toggle('cooling',this.shieldCooldown>0);$('#ability').style.setProperty('--charge',`${100-Math.ceil(this.shieldCooldown/30*100)}%`);$('#powers').innerHTML=[this.boost>0?`<span class="power">⚡ BOOST ${this.boost.toFixed(0)}s</span>`:'',this.magnet>0?`<span class="power">◎ MAGNET ${this.magnet.toFixed(0)}s</span>`:'',this.slow>0?`<span class="power">◷ SLOW ${this.slow.toFixed(0)}s</span>`:'',this.shield>0?'<span class="power">⬡ SHIELD</span>':''].join('')}
 updateMissions(){const values:any={distance:this.distance,coins:this.runCoins,survive:this.elapsed,avoid:this.avoided,mochaCoins:this.mochaCoins,shields:this.shieldsUsed};MISSIONS.forEach(m=>{if(values[m.id]>=m.goal&&!this.completed.includes(m.id)&&!save.missionClaims.includes(m.id)){this.completed.push(m.id);audio.power();this.flashLabel('MISSION COMPLETE!')}})}
 pause(){if(this.ended||this.paused)return;this.paused=true;this.hold=false;this.time.paused=true;this.tweens.pauseAll();show(`<div class="panel center"><div class="eyebrow">TAKE A BREATHER</div><h1>PAUSED ⏸</h1><p class="sub">Mocha insists this was all part of the plan.</p><div class="actions">${btn('▶ RESUME','resume','gold')}${btn('↻ RESTART','restart')}${btn('⌂ MENU','menu','ghost')}</div></div>`);btns()}
 resume(){if(!this.paused)return;this.paused=false;this.time.paused=false;this.tweens.resumeAll();hide();audio.unlock()}
 gameOver(){if(this.ended)return;this.ended=true;this.hold=false;this.cameras.main.shake(350,.017);this.saeid.setTint(0xff5555);this.mocha.rotation=-.35;this.emit(265,this.playerY,0xff783a,26);audio.hit();save.wallet+=this.runCoins;save.totalDistance+=this.distance;for(const id of this.completed)if(!save.missionClaims.includes(id)&&!save.pendingMissionClaims.includes(id))save.pendingMissionClaims.push(id);let newBest=this.score>save.best;if(newBest)save.best=Math.floor(this.score);if(!save.achievements.includes('first'))save.achievements.push('first');if(save.totalDistance>=500&&!save.achievements.includes('rookie'))save.achievements.push('rookie');if(save.totalDistance>=3000&&!save.achievements.includes('speed'))save.achievements.push('speed');if(save.wallet>=500&&!save.achievements.includes('collector'))save.achievements.push('collector');if(this.shieldsUsed&&!save.achievements.includes('guardian'))save.achievements.push('guardian');if(this.mode==='rescue'&&!save.achievements.includes('rescue'))save.achievements.push('rescue');persist();this.endUI(newBest)}
 endUI(newBest=false){hint.classList.add('hidden');hud.classList.add('hidden');show(`<div class="panel center"><div class="eyebrow">MISSION DEBRIEF · ${WORLDS[this.world].name}</div><h1 class="hero-title">${newBest?'NEW RECORD!':'GAME OVER'}</h1><p class="sub">${this.mode==='rescue'?'Mocha approves. Barely.':'The lab might have won this round. Your cat disagrees.'}</p><div class="grid2"><div class="tile"><div class="tiny">DISTANCE</div><h2>${fmt(this.distance)} m</h2></div><div class="tile"><div class="tiny">SCORE</div><h2>${fmt(this.score)}</h2></div><div class="tile"><div class="tiny">COINS EARNED</div><h2 class="price">◈ ${fmt(this.runCoins)}</h2></div><div class="tile"><div class="tiny">PERSONAL BEST</div><h2>${fmt(save.best)}</h2></div></div>${this.completed.length?`<h3>🎯 Completed Missions</h3>${this.completed.map(id=>{const m=MISSIONS.find(x=>x.id===id)!;return `<div class="row-item"><b>${m.name}</b>${save.missionClaims.includes(id)?'<span class="tag">CLAIMED</span>':btn('CLAIM ◈ '+m.award,'claim:'+id,'gold')}</div>`}).join('')}`:''}<div class="actions">${btn('↻ PLAY AGAIN','restart','gold')}${btn('⌂ MAIN MENU','menu','ghost')}</div></div>`);btns()}
}
let allowPortrait=false;function syncRotate(){const v=!allowPortrait&&innerWidth<730&&innerHeight>innerWidth;$('#rotate').classList.toggle('hidden',!v)}$('#portrait-continue').addEventListener('click',()=>{allowPortrait=true;syncRotate()});window.addEventListener('resize',syncRotate);syncRotate();
game=new Phaser.Game({type:Phaser.AUTO,parent:'game',width:W,height:H,transparent:false,backgroundColor:'#071328',render:{antialias:true,pixelArt:false},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},input:{activePointers:3},scene:[Menu,Runner],fps:{target:60,forceSetTimeOut:false}});
